---
kind: pipeline
type: docker
trigger:
  ref:
    - refs/heads/master
    - refs/pull/**
    - refs/tags/*
steps:
  - name: install
    image: node
    commands:
      - npm ci
  - name: lint
    image: node
    commands:
      - npm run lint
  - name: build
    image: node
    commands:
      - npm run build
  - name: publish
    image: node
    when:
      status:
        - success
      event:
        - tag
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - npm set registry https://registry.npmjs.org
      - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm publish --access public
---
kind: signature
hmac: fd3766cae95fa56e6b34e5b117e68f835e3a12e6192b7c0a65fd8522106423a8

...
