---
kind: pipeline
type: docker
trigger:
  ref:
    - refs/heads/master
    - refs/pull/**
    - refs/tags/*
steps:
  - name: install
    image: node
    commands:
      - npm ci
  - name: lint
    image: node
    commands:
      - npm run lint
  - name: build
    image: node
    commands:
      - npm run build
  - name: publish
    image: node
    when:
      status:
        - success
      event:
        - tag
    environment:
      NPM_TOKEN:
        from_secret: OPSVENT_NPM
    commands:
      - npm set registry https://registry.npmjs.org
      - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm publish --access public
---
kind: signature
hmac: bc5bba3646273ea9406cabcd3de1b49f81b4a1376017651307791403fcda0a82

...
